import = [
   "~/.config/alacritty/catppuccin-macchiato.toml"
]

[font]
size = 12.0

[font.normal]
family= "DroidSansM Nerd Font"
style = "Regular"

[window]
opacity = 0.7
padding = { x = 15, y = 15}



